[workspace]
resolver = "2"
members = ["core", "ipc", "service", "src-tauri"]

[workspace.package]
edition = "2021"
publish = false

# tauri-app scaffold default: see https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
